# Generated by Django 5.1.4 on 2024-12-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Project',
            new_name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='brand',
            field=models.CharField(default='Desconocida', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='model',
            field=models.CharField(default='modelo desconocida', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, default='3000', max_digits=10),
            preserve_default=False,
        ),
    ]
